<script setup lang="ts"></script>

<template>
  <div class="about">
    <div class="title">
      <h2>About</h2>
    </div>
      <div class="bio">
        <img src="../assets/ck/ck_pp.png" alt="profile_picture" />
        <div class="text">
        <p id="hi">
        Hi I am <span>Cihan</span> !
        </p>
          <p>
            I am 20, I live in
            <span>France</span> at Mâcon. <br>  Currently studiying
            <span>computer science</span> at IUT of Dijon. <br> I will integrate
            <span>ESGI Lyon</span> in web developpement next year. <br> I am
            passionate about <span>web</span> programming, <span>photography</span>
            and <span>cats</span>. <br> I make projects such as
            <span>web sites</span>, <span>web apps</span> and
            <span>softwares</span> to have fun. <br> Currently seeking for a
            <span>work-study contract</span> don't hesitate to contact me if
            you're <span>interested</span> in my profile.
          </p>
        </div>
      </div>
  </div>
</template>

<style lang="scss" scoped>
$white: #fff;
$red: #fa4454;
$black: #000;

.about {
  position: relative;
  height: 100vh;
}

.title {
  width: 100%;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  align-items: center;
  position: absolute;
  top: 28%;
  margin-top: -100px;
  text-align: center;
}

.bio {
  width: 100%;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  align-items: center;
  position: absolute;
  top: 40%;
  margin-top: -100px;
} 

.bio img {
  width: 250px;
}

.text {
  width: 100%;
  max-width: 53%;
  text-align: center;
  margin-top: 25px;
}

p {
  font-size: 24px;
}

#hi {
  margin-bottom: 10px;
}


/* ----------------------------------------------
 * Generated by Animista on 2022-3-13 18:12:17
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-expand-fwd-bottom
 * ----------------------------------------
 */
@-webkit-keyframes tracking-in-expand-fwd-bottom {
  0% {
    letter-spacing: -0.5em;
    -webkit-transform: translateZ(-700px) translateY(500px);
    transform: translateZ(-700px) translateY(500px);
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    -webkit-transform: translateZ(0) translateY(0);
    transform: translateZ(0) translateY(0);
    opacity: 1;
  }
}
@keyframes tracking-in-expand-fwd-bottom {
  0% {
    letter-spacing: -0.5em;
    -webkit-transform: translateZ(-700px) translateY(500px);
    transform: translateZ(-700px) translateY(500px);
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    -webkit-transform: translateZ(0) translateY(0);
    transform: translateZ(0) translateY(0);
    opacity: 1;
  }
}
</style>
