<script setup lang="ts">



</script>

<template>
    <div class="landing">
        <div class="content">
            <p id="iam">
                I am <span>Cihan</span>, a <span>full stack</span> developer
            </p>
            <p id="moto">
                <span>“</span>The best way to learn is to practice<span>”</span>
            </p>
        </div>
    </div>
</template>

<style lang="scss" scoped>
$white: #fff;
$red: #fa4454;
$black: #000;

.landing {
    position: relative;
    height: 100vh;
}

.content {
    width: 100%;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    align-items: center;
    position: absolute;
    top: 50%;
    height: 10px;
    margin-top: -100px;
}

#iam {
    font-size: 48px;
    text-align: center;
    font-family: "Ubuntu", sans-serif;
    padding: 50px 0px 0px 0px;
    -webkit-animation: tracking-in-expand-fwd-bottom 1s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
	        animation: tracking-in-expand-fwd-bottom 1s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
}

#moto {
    font-size: 25px;
    font-style: italic;
    flex: 1;
    -webkit-animation: tracking-in-expand-fwd-bottom 1.2s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
	        animation: tracking-in-expand-fwd-bottom 1.2s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
}

span {
    color: $red;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-3-13 18:12:17
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-expand-fwd-bottom
 * ----------------------------------------
 */
@-webkit-keyframes tracking-in-expand-fwd-bottom {
  0% {
    letter-spacing: -0.5em;
    -webkit-transform: translateZ(-700px) translateY(500px);
            transform: translateZ(-700px) translateY(500px);
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    -webkit-transform: translateZ(0) translateY(0);
            transform: translateZ(0) translateY(0);
    opacity: 1;
  }
}
@keyframes tracking-in-expand-fwd-bottom {
  0% {
    letter-spacing: -0.5em;
    -webkit-transform: translateZ(-700px) translateY(500px);
            transform: translateZ(-700px) translateY(500px);
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    -webkit-transform: translateZ(0) translateY(0);
            transform: translateZ(0) translateY(0);
    opacity: 1;
  }
}

</style>