<script setup lang="ts">
import projects from '../composable/projects';
import { useRoute } from 'vue-router';

const route = useRoute();

const projet = projects.projects.find(project => project.idProject.toString() == route.params.id)

function getImageUrl(name: any) {

    return new URL(`/projects/VToffle/${name}`, import.meta.url).href
}

</script>

<template>
    <div class="detail">
        <div class="title">
            <h2>{{ projet?.title }}</h2>
        </div>
        <div class="wrap">
            <div class="description">
                <p>
                    <span id="info">Description :</span>
                </p>
                <p id="para">{{ projet?.detailDescription }}</p>
                <p id="info">
                    <span>Technologies :</span>
                </p>
                <div class="technologies">
                    <p v-for="tech in projet?.detailTechnologies">{{ tech }}</p>
                </div>
                <div class="meta">
                    <p id="info">
                        <span>Duration :</span>
                        {{ projet?.detailDuration }}
                    </p>
                    <p id="info">
                        <span>Teams Member :</span>
                        {{ projet?.detailTeam }}
                    </p>
                    <p id="info">
                        <span>State :</span>
                        {{ projet?.detailState }}
                    </p>
                </div>
            </div>
            <!-- getImageUrl(projet?.detailImagePath) -->
            <img :src="projet?.detailImagePath" />
        </div>
    </div>
</template>

<style lang="scss" scoped>
$white: #fff;
$red: #fa4454;
$black: #000;

.detail {
    height: 100vh;
    -webkit-animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
    animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}

.wrap {
    display: flex;
    justify-content: space-between;
    padding-top: 70px;
}

.description {
    flex-grow: 1;
    display: flex;
    flex-direction: column;
}

.technologies {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    padding-right: 25px;
}

.technologies p {
    margin: 0px 0px 25px 25px;
    font-weight: 500;
    width: 80%;
}

img {
    width: 400px;
    // flex-grow: 1;
}

#info {
    font-size: 20px;
    padding: 0px 25px 25px 0px;
}

.meta {
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: space-between;
    flex-grow: 1;
    width: 80%;
}

#para {
    font-size: 20px;
    letter-spacing: 2.75;
    text-align: justify;
    padding: 25px 25px 25px 25px;
    max-width: 80%;
}

@media (max-width: 1100px) {
    .detail {
        height: 100vh;
        -webkit-animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
        animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
    }

    .title {
        padding-top: 70px;
    }

    .wrap {
        display: flex;
        flex-direction: column-reverse;
        padding-top: 70px;
        justify-content: center;
        text-align: center;
    }

    .description {
        flex-grow: 1;
        display: flex;
        flex-direction: column;
    }

    .technologies {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        padding-right: 0px;
        align-items: center;
    }

    .technologies p {
        // margin: 5px 2px 5px 2px;
        margin: auto;
        margin-bottom: 8px;
        font-weight: 500;
        width: 80%;
    }

    img {
        width: 300px;
        align-self: center;
        // flex: 1;
        // flex-grow: 1;
    }

    #info {
        font-size: 20px;
        padding: 25px 0px 25px 0px;
    }

    .meta {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-between;
        align-self: center;
        flex-grow: 1;
        padding: 0px 5px 0px 0px;
        width: 80%;
    }

    #para {
        font-size: 20px;
        letter-spacing: 2.75;
        text-align: justify;
        text-align-last: center;
        padding: 25px 25px 0px 25px;
        width: 100%;
        align-self: center;
        line-height: 1.5;
        // max-width: 80%;
    }
}
/* ----------------------------------------------
 * Generated by Animista on 2022-3-15 12:28:31
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
    0% {
        opacity: 0;
    }
    100% {
        opacity: 1;
    }
}
@keyframes fade-in {
    0% {
        opacity: 0;
    }
    100% {
        opacity: 1;
    }
}
</style>
