<script setup lang="ts">
import TheProject from './utils/TheProject.vue';
import projects from '../composable/projects';

let project = projects.projects


</script>

<template>
  <div class="projects">
    <div class="title">
      <h2>Projects</h2>
    </div>
    <div class="project-grid">
      <div v-for="project in projects.projects">
        <TheProject :idProject="project.idProject" :title="project.title" :desc="project.desc" :imagePath="project.imagePath" :cardColor="project.cardColor" />
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
$white: #fff;
$red: #fa4454;
$black: #000;
  
  @media only screen and (min-width: 1600px) {
    .projects {
  position: relative;
  height: 120vh;
  -webkit-animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  text-align: center;
}

.project-grid {
    width: 100%;
    position: absolute;
    margin-top: 70px;
    display: grid;
    grid-template-columns: 33.3333333333333333333333333333333333333333333333333333333333333333333333% 33.3333333333333333333333333333333333333333333333333333333333333333333333% 33.3333333333333333333333333333333333333333333333333333333333333333333333%;
    text-align: center;
    align-items: center;
    display: grid;
    grid-row-gap: 80px;
}
  }


@media only screen and (max-width: 900px) {
  
.projects {
  position: relative;
  height: 120vh;
  -webkit-animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  text-align: center;
  width: 100%;
}

.title {
  padding-top: 70px;
}

.project-grid {
    width: 100%;
    position: absolute;
    margin-top: 70px;
    display: grid;
    grid-template-columns: 33.3333333333333333333333333333333333333333333333333333333333333333333333% 33.3333333333333333333333333333333333333333333333333333333333333333333333% 33.3333333333333333333333333333333333333333333333333333333333333333333333%;
    text-align: center;
    align-items: center;
    display: grid;
    grid-row-gap: 80px;
    grid-template-columns: 1fr;
}
}

@media (min-width:900px) and (max-width:1600px) {
  
.projects {
  position: relative;
  height: 120vh;
  -webkit-animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  text-align: center;
  width: 100%;
  padding-bottom: 210vh;
}

.project-grid {
    width: 100%;
    position: absolute;
    margin-top: 70px;
    display: grid;
    grid-template-columns: 33.3333333333333333333333333333333333333333333333333333333333333333333333% 33.3333333333333333333333333333333333333333333333333333333333333333333333% 33.3333333333333333333333333333333333333333333333333333333333333333333333%;
    text-align: center;
    align-items: center;
    display: grid;
    grid-row-gap: 80px;
    grid-template-columns: 2fr 2fr;
}
}

/* ----------------------------------------------
 * Generated by Animista on 2022-3-15 22:5:36
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-blurred-bottom
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-blurred-bottom {
  0% {
    -webkit-transform: translateY(1000px) scaleY(2.5) scaleX(0.2);
            transform: translateY(1000px) scaleY(2.5) scaleX(0.2);
    -webkit-transform-origin: 50% 100%;
            transform-origin: 50% 100%;
    -webkit-filter: blur(40px);
            filter: blur(40px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) scaleY(1) scaleX(1);
            transform: translateY(0) scaleY(1) scaleX(1);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
    -webkit-filter: blur(0);
            filter: blur(0);
    opacity: 1;
  }
}
@keyframes slide-in-blurred-bottom {
  0% {
    -webkit-transform: translateY(1000px) scaleY(2.5) scaleX(0.2);
            transform: translateY(1000px) scaleY(2.5) scaleX(0.2);
    -webkit-transform-origin: 50% 100%;
            transform-origin: 50% 100%;
    -webkit-filter: blur(40px);
            filter: blur(40px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) scaleY(1) scaleX(1);
            transform: translateY(0) scaleY(1) scaleX(1);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
    -webkit-filter: blur(0);
            filter: blur(0);
    opacity: 1;
  }
}


/* ----------------------------------------------
 * Generated by Animista on 2022-3-15 12:28:31
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
</style>
