<script setup lang="ts"></script>

<template>
  <div class="skills">
    <div class="title">
      <h2>Skills</h2>
    </div>
    <div class="skills-grid">
      <div class="skill">
        <img src="../assets/icons/skills/vue.svg" alt="vueicon" />
        <h3 class="skill-name">Vue</h3>
        <p>Advanced understanding of the framework</p>
      </div>
      <div class="skill">
        <img src="../assets/icons/skills/javascript.svg" alt="javascripticon" />
        <h3 class="skill-name">Javascript</h3>
        <p>Intermediate understanding of the language</p>
      </div>
      <div class="skill">
        <img src="../assets/icons/skills/postgresql.svg" alt="postgresqlicon" />
        <h3 class="skill-name">PostgreSQL</h3>
        <p>Capable of advanced queries</p>
      </div>
      <div class="skill">
        <img id="prisma" src="../assets/icons/skills/prisma.svg" alt="prismaicon" />
        <h3 class="skill-name">Prisma</h3>
        <p>Good understanding and using of the ORM</p>
      </div>
      <div class="skill">
        <img src="../assets/icons/skills/java.svg" alt="javaicon" />
        <h3 class="skill-name">Java</h3>
        <p>Intermediate understanding of the language</p>
      </div>
      <div class="skill">
        <img src="../assets/icons/skills/nodejs.svg" alt="nodejsicon" />
        <h3 class="skill-name">NodeJS</h3>
        <p>Good understanding of the service</p>
      </div>
      <div class="skill">
        <img id="docker" src="../assets/icons/skills/docker.svg" alt="dockericon" />
        <h3 class="skill-name">Docker</h3>
        <p>Beginner at Docker</p>
      </div>
      <div class="skill">
        <img src="../assets/icons/skills/angular.svg" alt="angularicon" />
        <h3 class="skill-name">Angular</h3>
        <p>Intermediate understanding of the framework</p>
      </div>
      <div class="skill">
        <img src="../assets/icons/skills/vite.svg" alt="viteicon" />
        <h3 class="skill-name">Vite</h3>
        <p>Beginner at Vite</p>
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
$white: #fff;
$red: #fa4454;
$black: #000;

.skills {
  position: relative;
  height: 140vh;
  -webkit-animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  text-align: center;
}

.skills-grid {
  width: 100%;
  position: absolute;
  padding-top: 70px;
  display: grid;
  grid-template-columns: 33.3333333333333333333333333333333333333333333333333333333333333333333333% 33.3333333333333333333333333333333333333333333333333333333333333333333333% 33.3333333333333333333333333333333333333333333333333333333333333333333333%;
  text-align: center;
  align-items: center;
	-webkit-animation: slide-in-blurred-bottom 1s cubic-bezier(0.230, 1.000, 0.320, 1.000) both;
	        animation: slide-in-blurred-bottom 1s cubic-bezier(0.230, 1.000, 0.320, 1.000) both;
}

.skill {
  padding: 0px 10px 100px;
  width: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: space-between;
}

img {
  width: 100px;
}


h3 {
  color: $red;
  font-size: 24px;
  font-weight: 500;
  padding: 8px 0px 14px 0px;
  font-family: 'Ubuntu', sans-serif;
}

p {
  text-align: center;
  font-size: 1.4rem;
  max-width: 50%;
  height: 20px;
}

#prisma {
  width: 80px;
}

#docker {
  width: 120px;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-3-15 22:5:36
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-blurred-bottom
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-blurred-bottom {
  0% {
    -webkit-transform: translateY(1000px) scaleY(2.5) scaleX(0.2);
            transform: translateY(1000px) scaleY(2.5) scaleX(0.2);
    -webkit-transform-origin: 50% 100%;
            transform-origin: 50% 100%;
    -webkit-filter: blur(40px);
            filter: blur(40px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) scaleY(1) scaleX(1);
            transform: translateY(0) scaleY(1) scaleX(1);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
    -webkit-filter: blur(0);
            filter: blur(0);
    opacity: 1;
  }
}
@keyframes slide-in-blurred-bottom {
  0% {
    -webkit-transform: translateY(1000px) scaleY(2.5) scaleX(0.2);
            transform: translateY(1000px) scaleY(2.5) scaleX(0.2);
    -webkit-transform-origin: 50% 100%;
            transform-origin: 50% 100%;
    -webkit-filter: blur(40px);
            filter: blur(40px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) scaleY(1) scaleX(1);
            transform: translateY(0) scaleY(1) scaleX(1);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
    -webkit-filter: blur(0);
            filter: blur(0);
    opacity: 1;
  }
}


/* ----------------------------------------------
 * Generated by Animista on 2022-3-15 12:28:31
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
</style>
